### PR TITLE
Extract retry logic into scripts/retry

### PR DESCRIPTION
**Pull request by morganchristiansson**
I like the consistency in the copy paste here..
All instances are identical and find-replace easily addresses the duplication :+1: 

TIMEOUT/RETRIES have same value everywhere

### CODE REVIEW

**Comment by morganchristiansson** [comment]
As builds didn't trigger automatically I created PR on my fork to run builds https://github.com/morganchristiansson/docker-ansible/pull/3

**Comment by morganchristiansson** [comment]
If this is merged it will significantly reduce the diff in #74

**Review by cytopia — APPROVED** [review]
Let's have this one be merged first, then there are so many changes in the orther PR, once rebaed.

**Comment by morganchristiansson** [comment]
Hmm lint is failing. I thought it would start working in PR here. I've not had lint run in any of my GH action builds...
```
[ERR] New Tag required in .github/workflows/nightly.yml: 0.34
```

**Comment by cytopia** [comment]
> Hmm lint is failing. I thought it would start working in PR here. I've not had lint run in any of my GH action builds...
> 
> ```
> [ERR] New Tag required in .github/workflows/nightly.yml: 0.34
> ```

The fail is fine. Always just a reminder to myself to update the nightly workflow in case I want to release a new tag.

It might have worked in your fork due to lack of tags alltogether

**Comment by cytopia** [comment]
> I don't know how you managed to push to my branch in my fork however?

This somehow always works via the webui in the review tab. I can (for every file you've changed) click on "edit" and commit changes.

**Pull request merged**
